version: "3"
services:
  proxy:
    image: thelebster/docker-squid-simple-proxy
    ports:
      - ${PORT}:3128
      - ${SSH_PORT}:22
    volumes:
      - ./logs:/var/log/squid
      - ./cache:/var/spool/squid
    restart: always
    env_file:
      - ".env"
    extra_hosts:
      host.docker.internal: host-gateway # a bugfix just for linux users ;)