version: "3"
services:
  proxy:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - ./logs:/var/log/squid
      - ./cache:/var/spool/squid
    restart: always
    env_file:
      - ".env"
    extra_hosts:
      host.docker.internal: host-gateway # a bugfix just for linux users ;)